# Generated by Django 5.2.7 on 2025-10-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kino', '0002_movie_original_title_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app_kino.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app_kino.session', verbose_name='Сеанс'),
        ),
    ]
