# Generated by Django 5.2.7 on 2025-10-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kino', '0003_alter_session_movie_alter_ticket_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app_kino.hall', verbose_name='Зал'),
        ),
    ]
