# Generated by Django 5.2.7 on 2025-10-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kino', '0004_alter_session_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app_kino.cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_kino.cinema', verbose_name='Кинотеатр'),
        ),
    ]
